### ISSUE TITLE
Add possibility to colorize the icons and labels

### ISSUE THREAD

**Issue by giacu92** [LazeMSS/OctoPrint-TopTemp#17]
When using Dark settings on octoprint icons and label cannot be read as the gray is very similar to topbar

**Comment by giacu92** [comment]
![Cattura](https://user-images.githubusercontent.com/16169618/105893276-2bc66700-6013-11eb-982d-a60d41a8919a.PNG)

**Comment by LazeMSS** [comment]
Well there is no color defined in my plugin. The theme should change default font colour. I will look later and maybe add an option to set label color and icon color

**Comment by shadowpanther** [comment]
Proper colors for navbar elements seem to come from .navbar-text class. But just adding this class anywhere in your layout messes the navbar because the dimension it sets are suited for one-line elements.

So, I propose:
- add a class to the container:
```
<li id="navbar_plugin_toptemp" class="navbar-text" data-bind="allowBindings: true" style="margin-right: 4px; margin-left: 4px;">
```
- override the line-height back to the previous value (I don't know if if there is a better way to do this):
```
#navbar_plugin_toptemp > div {
	margin-top: -2px;
	line-height: 20px;
}
```

**Comment by LazeMSS** [comment]
@giacu92 and @shadowpanther please try the latest release:

https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.0.3

I'm closing for now - if not fixed please reopen this :)

**Comment by giacu92** [comment]
![45AAAB1F-5B57-4B4F-B9F9-1258F130366B](https://user-images.githubusercontent.com/16169618/106608547-d33c2000-6564-11eb-85d8-6b12ecb2e5ad.jpeg)

working flawlessly :) thanks!
