### ISSUE TITLE
Make all information from the M105 command available

### ISSUE THREAD

**Issue by fdraeger** [LazeMSS/OctoPrint-TopTemp#18]
This request asks to provide a selection of temperatures returned from the M105 command.

I was trying to display the probe sensor temp which was not possible as custom temp via executing a shell command.

My printer (Caribou3D) provides:

`Send: M105
Recv: ok T:18.3 /0.0 B:18.6 /0.0 T0:18.3 /0.0 @:0 B@:0 P:19.3 A:29.2`

So this request is to provide a selection to allow to pick P (Probe) and A (Ambient) temperatures to be shown.

**Comment by LazeMSS** [comment]
Im looking into it :)

**Comment by fila612** [comment]
i'm also interested for this enhancement

**Comment by LazeMSS** [comment]
I have it running in a test version now. Will release it after the next release.

**Comment by LazeMSS** [comment]
This is fixed in the next release - please test/try by following:
```
Settings -> Plugin Manager
At the bottom click "Get more.."
In the input field below "... from URL" paste in: https://github.com/LazeMSS/OctoPrint-TopTemp/archive/develop.zip
Click Install
```

**Comment by LazeMSS** [comment]
Closing - fixed in: https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.1.0

Please reopen if not fixed

**Comment by fila612** [comment]
thanks for that feature, on my system it works only for PINDA Probe, not for ambient.
settings for probe and ambient quite similar, but no values showing for ambient.
So I can't reopen this ticket, maybe someone else could do that, or I'm the only one with that error.

**Comment by LazeMSS** [comment]
1. Have you tried turning of "Only show while printer is printing" if thats enabled?
2. With the data you have in the screenshot choosing "Type" = "From printer" and selecting the predefined types - they should both work.

**Comment by fila612** [comment]
Hi, I've compared the PINDA and the ambient settings and they are mostly the same, except the regex to catch the values.
I've nothing changed and I'm using the predefinitions and I think also that they should work (the only difference is the "A" instead of "P"....
The option "Only show while printer is printing" was not set.

here are some samples of M105:
ok T:234.8 /235.0 B:75.0 /75.0 T0:234.8 /235.0 @:63 B@:29 P:62.5 A:50.3
ok T:234.8 /235.0 B:75.0 /75.0 T0:234.8 /235.0 @:62 B@:27 P:62.6 A:50.3
ok T:235.1 /235.0 B:75.0 /75.0 T0:235.1 /235.0 @:58 B@:29 P:62.5 A:50.2
ok T:234.8 /235.0 B:75.0 /75.0 T0:234.8 /235.0 @:65 B@:33 P:62.5 A:50.2
ok T:234.1 /235.0 B:75.0 /75.0 T0:234.1 /235.0 @:74 B@:30 P:62.3 A:50.3
ok T:234.0 /235.0 B:75.0 /75.0 T0:234.0 /235.0 @:73 B@:34 P:62.2 A:50.4
ok T:234.7 /235.0 B:74.9 /75.0 T0:234.7 /235.0 @:61 B@:43 P:62.1 A:50.3

**Comment by LazeMSS** [comment]
Could you post a screenshot of the settings?

**Comment by fila612** [comment]
sure
<img width="998" alt="Bildschirmfoto 2021-02-22 um 12 50 30" src="https://user-images.githubusercontent.com/29542374/108704688-a5674d00-750c-11eb-818d-214e19b638a8.png">
<img width="998" alt="Bildschirmfoto 2021-02-22 um 12 50 44" src="https://user-images.githubusercontent.com/29542374/108704695-a7311080-750c-11eb-8bdf-65c72e6d2461.png">

**Comment by LazeMSS** [comment]
Try with this pattern:
`(?:T|T0):.*? A:([^ ]+)[^<>\r\n]`
I think I might have made a mistake - it includes the newline at the end :/

**Comment by fila612** [comment]
thanks, that works!!! :) 👍 
<img width="984" alt="Bildschirmfoto 2021-02-22 um 12 56 16" src="https://user-images.githubusercontent.com/29542374/108705328-730a1f80-750d-11eb-8b68-ca06714872ea.png">

**Comment by LazeMSS** [comment]
Great - will fix in the next version - thanks for the feedback.
